#!/bin/bash

python main.py \
--do_train --do_eval \
--source_lang='en' --target_lang='cm' \
--output_dir='models/newobj_tmp' \
--per_device_train_batch_size=8 \
--per_device_eval_batch_size=8 \
--gradient_accumulation_steps=2 \
--overwrite_output_dir=True \
--predict_with_generate \
--train_file='../cm_data/cmi_control_train_cmi_vector.tsv' \
--validation_file='../cm_data/cmi_control_dev_cmi_vector.tsv' \
--train_file_classify='train_classify.tsv' \
--validation_file_classify='dev_classify.tsv' \
--load_best_model_at_end \
--metric_for_best_model='loss' \
--num_train_epochs=3.0 \
--learning_rate=5e-4 \
--eval_steps=10 \
--save_steps=1000 \
--evaluation_strategy='steps' \
--save_strategy='steps' \
--lr_scheduler_type='constant' \
--generation_num_beams=1 \
--generation_max_length=128 \
--optim='adafactor' \
--max_source_length=128 \
--max_target_length=128 \
--with_tracking=True \
--max_train_samples=100 \
--max_train_classify_samples=100
